// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { ANT_LING_MODELS } from "./providers/ant-ling.models.ts";
import { AZURE_OPENAI_RESPONSES_MODELS } from "./providers/azure-openai-responses.models.ts";
import { DEEPSEEK_MODELS } from "./providers/deepseek.models.ts";
import { MISTRAL_MODELS } from "./providers/mistral.models.ts";
import { OPENAI_MODELS } from "./providers/openai.models.ts";
import { OPENAI_CODEX_MODELS } from "./providers/openai-codex.models.ts";
import { OPENROUTER_MODELS } from "./providers/openrouter.models.ts";
import { QWEN_TOKEN_PLAN_MODELS } from "./providers/qwen-token-plan.models.ts";
import { QWEN_TOKEN_PLAN_CN_MODELS } from "./providers/qwen-token-plan-cn.models.ts";
import { VERCEL_AI_GATEWAY_MODELS } from "./providers/vercel-ai-gateway.models.ts";

export const MODELS: {
	readonly "ant-ling": typeof ANT_LING_MODELS;
	readonly "azure-openai-responses": typeof AZURE_OPENAI_RESPONSES_MODELS;
	readonly "deepseek": typeof DEEPSEEK_MODELS;
	readonly "mistral": typeof MISTRAL_MODELS;
	readonly "openai": typeof OPENAI_MODELS;
	readonly "openai-codex": typeof OPENAI_CODEX_MODELS;
	readonly "openrouter": typeof OPENROUTER_MODELS;
	readonly "qwen-token-plan": typeof QWEN_TOKEN_PLAN_MODELS;
	readonly "qwen-token-plan-cn": typeof QWEN_TOKEN_PLAN_CN_MODELS;
	readonly "vercel-ai-gateway": typeof VERCEL_AI_GATEWAY_MODELS;
} = {
	"ant-ling": ANT_LING_MODELS,
	"azure-openai-responses": AZURE_OPENAI_RESPONSES_MODELS,
	"deepseek": DEEPSEEK_MODELS,
	"mistral": MISTRAL_MODELS,
	"openai": OPENAI_MODELS,
	"openai-codex": OPENAI_CODEX_MODELS,
	"openrouter": OPENROUTER_MODELS,
	"qwen-token-plan": QWEN_TOKEN_PLAN_MODELS,
	"qwen-token-plan-cn": QWEN_TOKEN_PLAN_CN_MODELS,
	"vercel-ai-gateway": VERCEL_AI_GATEWAY_MODELS,
};
